### PR TITLE
Section 2 - Team 2

### PR DESCRIPTION
**Pull request by kevinrpb**
Added file with our team's names

### CODE REVIEW

**Comment by gildir** [comment]
The discussion area for a pull request is where the GTA and I will discuss any changes to your pull requests. In this case, this this request is merely a participation activity, but on other assignments when I or the TA closes the pull request, you can assume your work has been accepted for grading and a grade within one week of your submission.

In this case, we cannot currently accept your pull request as there are only three people in your text file. Please get the contributions from your last team member and update the pull request!

**Comment by kevinrpb** [comment]
Andrew, the fourth member of the group, doesn't own a laptop. Therefore he couldn't contribute to the repo in the class. As it was an activity and not an actual assignment we thought it was ok to go trhough the whole process regardless of not all the info being there. 

Should he anyway commit his changes and make another PR then?

**Comment by kevinrpb** [comment]
Now everybody made their changes.

**Comment by gildir** [comment]
Awesome, good job guys!

**Pull request merged**
